name: Mon Workflow

on:
  push:
    branches: [develop]

jobs:
  test-memory:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test JPG files
        run: |
          for file in $(find . -name '*.jpg'); do
            file $(file)
          done
  build-memory:
    runs-on: [self-hosted, linux, x64]
    needs: test-memory

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t doudouchevalier/memory:latest .
  push-memory:
    runs-on: [self-hosted, linux, x64]
    needs: build-memory

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push doudouchevalier/memory:latest



  deploy-memory:
    runs-on: [self-hosted, linux, x64]
    needs: push-memory

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull doudouchevalier/memory:latest
            docker run -d -p 80:80 doudouchevalier/memory:latest
